---
- name: Set up vnstat config file
  template: src=templates/vnstat.conf.in dest=/etc/vnstat.conf mode=0755 owner=root group=root
  notify: restart vnstat

- name: Ininitalize vnstat
  command: vnstat -u -i {{ interface }}

