---
- group: name=vnstat state=present
- user: name=vnstat comment="vnstat" group=vnstat createhome=no system=yes shell=/bin/false home=/var/lib/vnstat

- file: path=/var/lib/vnstat state=directory mode=0755 owner=vnstat group=vnstat

- name: Set up vnstat config file
  template: src=templates/vnstat.conf.j2 dest=/etc/vnstat.conf mode=0755 owner=root group=root
  notify: restart vnstat

- name: Ininitalize vnstat
  command: sudo -u vnstat vnstat -u -i {{ vnstat_interface }}
  creates: /var/lib/vnstat/{{ vnstat_interface }}
